[preferred]
default = hyprland;gtk
org.freedesktop.impl.portal.FileChooser = termfilechooser
org.freedesktop.impl.portal.Secret = gnome-keyring
org.freedesktop.impl.portal.Settings = luminous
org.freedesktop.impl.portal.Inhibit = gtk
