#!/usr/bin/env bash

echo "Running Post Pull Script..."

yadm --yadm-dir $HOME/.config/yadm/dotfiles --yadm-data $HOME/.local/share/yadm/dotfiles decrypt

if [[ "$(yadm --yadm-dir $HOME/.config/yadm/dotfiles --yadm-data $HOME/.local/share/yadm/dotfiles config --get local.class)" == "wsl" ]]; then
  cp -vru "$HOME"/.config/wezterm/* /mnt/c/Users/Filipe/.config/wezterm/
fi
