#!/usr/bin/env bash

echo "Running Pre Commit script..."

yadm --yadm-dir $HOME/.config/yadm/dotfiles --yadm-data $HOME/.local/share/yadm/dotfiles encrypt

if [[ "$(yadm --yadm-dir $HOME/.config/yadm/dotfiles --yadm-data $HOME/.local/share/yadm/dotfiles config --get local.class)" == "wsl" ]]; then
  cp -vru /mnt/c/Users/Filipe/.config/wezterm/* "$HOME"/.config/wezterm/
fi
