[global]
workgroup = WORKGROUP
security = USER
map to guest = Bad User
guest account = nobody
logging = syslog

interfaces = eth0

;case sensitive = true
;default case = lower
;preserve case = no
;short preserve case = no

getwd cache = true
use sendfile = yes
aio read size = 1
aio write size = 1
deadtime = 15

[public]
path = /mnt/data/public
browseable = yes
guest only = yes
read only = no
