input {
  kb_layout = us
  kb_variant = intl
  numlock_by_default = true
  sensitivity = 0.0
  natural_scroll = false
  force_no_accel = true
  follow_mouse = 1
  touchpad {
    disable_while_typing = true
    natural_scroll = true
    scroll_factor = 0.5
    tap-to-click = true
    drag_lock = 1
    tap-and-drag = true
  }
}

device {
  name = ven_04f3:00-04f3:325f-touchpad
  sensitivity = 0.7
  scroll_method = 2fg
}

device {
  name = at-translated-set-2-keyboard
  kb_model = abnt2
  kb_layout = br
  kb_variant =
}