# ░█░█░▀█▀░█▀█░█▀▄░█▀█░█░█░░░█▀▄░█░█░█░░░█▀▀░█▀▀
# ░█▄█░░█░░█░█░█░█░█░█░█▄█░░░█▀▄░█░█░█░░░█▀▀░▀▀█
# ░▀░▀░▀▀▀░▀░▀░▀▀░░▀▀▀░▀░▀░░░▀░▀░▀▀▀░▀▀▀░▀▀▀░▀▀▀

windowrule = match:class .*, suppress_event = maximize
windowrule = match:class ^$, match:title ^$, match:xwayland true, match:float true, match:fullscreen false, match:pin false, no_focus on

windowrule = match:class ^(kvantummanager|qt5ct|nwg-look|filechooser)$, float on

windowrule = match:title [Mm]inecraft [0-9].*, content game
windowrule = match:class ^(steam_app.*|hl2_linux)$, content game

windowrule = match:initial_class steam, match:initial_title negative:Steam, float on
#windowrule = match:class firefox, match:initial_class Mozilla Firefox, match:title negative:Mozilla Firefox, float on
windowrule = match:initial_class .*, match:class Minecraft Launcher, float on

windowrule {
  name = games
  match:content = 3
  
  dim_around = off
  decorate = off
  no_anim = on
  no_shadow = on
  no_dim = on
  no_blur = on
  render_unfocused = on
  immediate = on
}
windowrule = match:class ^(dyinglightgame_x64_rwdi.exe|hl2_linux)$, immediate off

windowrule {
  name = xwayland-video-bridge-fixes
  match:class = xwaylandvideobridge

  no_initial_focus = true
  no_focus = true
  no_anim = true
  no_blur = true
  max_size = 1 1
  opacity = 0.0
}
