# ░█░█░▀█▀░█▀█░█▀▄░█▀█░█░█░░░█▀▄░█░█░█░░░█▀▀░█▀▀
# ░█▄█░░█░░█░█░█░█░█░█░█▄█░░░█▀▄░█░█░█░░░█▀▀░▀▀█
# ░▀░▀░▀▀▀░▀░▀░▀▀░░▀▀▀░▀░▀░░░▀░▀░▀▀▀░▀▀▀░▀▀▀░▀▀▀


windowrule = match:class .*, suppress_event = maximize
windowrule = match:class ^$, match:title ^$, match:xwayland true, match:float true, match:fullscreen false, match:pin false, no_focus on

windowrule {
  name = floating-apps
  match:class = ^(kvantummanager|qt5ct|nwg-look|filechooser)$
  
  float = on
}

windowrule {
  name = games
  match:content = 3

  no_shadow = on
  no_dim = on
  no_blur = on
  render_unfocused = on
  immediate = on
}

windowrule {
  name = xwayland-video-bridge-fixes
  match:class = xwaylandvideobridge

  no_initial_focus = true
  no_focus = true
  no_anim = true
  no_blur = true
  max_size = 1 1
  opacity = 0.0
}