Write-Host "`e[2mHalf`e[0m"
Write-Host "`e[2;3mHalf Italic`e[0m"
Write-Host "`e[2;4mHalf Underline`e[0m"
Write-Host "`e[2;5mHalf Blink`e[0m"
Write-Host "`e[2;7mHalf Inverse`e[0m"
Write-Host "`e[2;8mHalf Hidden`e[0m"
Write-Host "`e[2;9mHalf Strikethrough`e[0m"

Write-Host "`e[0mRegular`e[0m"
Write-Host "`e[3mRegular Italic`e[0m"
Write-Host "`e[4mRegular Underline`e[0m"
Write-Host "`e[5mRegular Blink`e[0m"
Write-Host "`e[7mRegular Inverse`e[0m"
Write-Host "`e[8mRegular Hidden`e[0m"
Write-Host "`e[9mRegular Strikethrough`e[0m"

Write-Host "`e[1mBold`e[0m"
Write-Host "`e[1;3mBold Italic`e[0m"
Write-Host "`e[1;4mBold Underline`e[0m"
Write-Host "`e[1;5mBold Blink`e[0m"
Write-Host "`e[1;7mBold Inverse`e[0m"
Write-Host "`e[1;8mBold Hidden`e[0m"
Write-Host "`e[1;9mBold Strikethrough`e[0m"