-- hl.env("ICONTHEME", "Papirus-Dark")
-- hl.env("FONT", "NotoSans Nerd Font Propo Regular")
-- hl.env("FONTSIZE", "12")
-- hl.env("DOCFONT", "NotoSerif Nerd Font Propo Regular")
-- hl.env("DOCFONTSIZE", "12")
-- hl.env("MONOFONT", "CaskaydiaMono Nerd Font Mono Regular")
-- hl.env("MONOFONTSIZE", "14")
hl.env("ELECTRON_FORCE_WINDOW_MENU_BAR", "1")
hl.env("MOZ_DISABLE_RDD_SANDBOX", "1")
-- hl.env("WLR_RENDERER", "vulkan")