transaction_log            /var/log/btrbk.log

backend_local_user         btrfs-progs-sudo

stream_buffer              256m

lockfile                   /var/lock/btrbk.lock

snapshot_preserve_min   2d
snapshot_preserve       14d

target_preserve_min     no
target_preserve         20d 10w *m

volume /
  snapshot_dir @snapshot
  target /mnt/data-hdd/linux/artix/backup
  subvolume @
  subvolume @home