#!/usr/bin/env bash

echo "Running Post Pull Script..."

yadm decrypt

if [[ "$(yadm config --get local.class)" == "wsl" ]]; then
  cp -vru "$HOME"/.config/wezterm/* /mnt/c/Users/Filipe/.config/wezterm/
fi
