#!/usr/bin/env bash

echo "Running Post Alt Script..."

read -d '\n' -ra alt_files <<<"$(command find -L "${YADM_HOOK_DIR}/system_alt" -type f -not -path '*/.git/*' -not -path '*/*##*/*' -not -name '*##*')"

sudo -v
if [[ -n $alt_files ]]; then
  for file in "${alt_files[@]}"; do
    dest="$(dirname "${file##*system_alt}")"
    sudo -n mkdir -p "$dest"
    sudo -n cp -vfu --preserve=mode,timestamps --reflink=never "$(readlink -f "$file")" "${dest}/${file##*/}"
  done
fi
