#!/usr/bin/env bash

echo "Running Post Alt Script..."

: "${SKIP_SYS_ALTS:=}"

read -d '\n' -ra alt_files <<< "$(command find -L "${YADM_HOOK_DIR}/system_alt" -type f -not -path '*/.git/*' -not -path '*/*##*/*' -not -name '*##*')"

if [[ -n "$alt_files" ]] && [[ -z "$SKIP_SYS_ALTS" ]]; then
  sudo -v || exit 1
  for file in "${alt_files[@]}"; do
    dest="$(dirname "${file##*system_alt}")"
    sudo -n mkdir -p "$dest"
    sudo -n cp -v -a -L --no-preserve=owership --update=older --reflink=never "$file" "${dest}/${file##*/}"
  done
fi
