#!/usr/bin/env bash

echo "Running Pre Commit script..."

yadm encrypt

if [[ "$(yadm config --get local.class)" == "wsl" ]]; then
  cp -vru /mnt/c/Users/Filipe/.config/wezterm/* "$HOME"/.config/wezterm/
fi
