# background =
# base =
# text =
# alternate_base =
# bright_text =
# accent =
# accent_secondary =
# h1_size =
# h2_size =
# h3_size =
font_size = $FONTSIZE
# small_font_size =
icon_theme = $ICONTHEME
font_family = $FONT
font_family_monospace = $MONOFONT
# rounding_large =
# rounding_small =
