general {
    lock_cmd = pidof hyprlock || hyprlock; loginctl unlock-session
#   unlock_cmd = notify-send "Welcome back!"
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd =  hyprctl dispatch "hl.dsp.dpms({ action = 'on' })"; loginctl unlock-session
#  ignore_dbus_inhibit = false
#  ignore_systemd_inhibit = false
}

# listener {
#   timeout = 630
#   on-timeout = loginctl lock-session
# }

listener {
  timeout = 600
  on-timeout = hyprctl dispatch "hl.dsp.dpms({ action = 'on' })"
  on-resume = hyprctl dispatch "hl.dsp.dpms({ action = 'off' })"
}
