--enable-features=UseOzonePlatform,WaylandWindowDecorations,AllowQt,VaapiVideoDecoder,VaapiIgnoreDriverChecks,Vulkan,DefaultANGLEVulkan,VulkanFromANGLE
--disable-features=UseSkiaRenderer
--gtk-version=4
--ozone-platform=wayland
--single-process
--password-store=gnome-libsecret
--disk-cache-dir=/tmp/electron-cache
--use-gl=angle
--use-angle=vulkan
--ignore-gpu-blocklist
--enable-zero-copy
--enable-gpu-rasterization
--disable-gpu-driver-bug-workaround
--use-cmd-decoder=passthrough
