#:schema https://yazi-rs.github.io/schemas/keymap.json

[mgr]
prepend_keymap = [
  { on = "<C-[>", run = "noop" },
  { on = "~", run = "noop" },
  { on = "w", run = "noop" },
  { on = "F", run = "plugin smart-filter", desc = "Smart filter" },
  { on = "!", for = "unix", run = 'shell "$SHELL" --block', desc = "Open $SHELL here" },
  { on = "!", for = "windows", run = 'shell "powershell.exe" -block', desc = "Open PowerShell here" },
  # { on = "d", for = "unix", run = 'shell -- gio trash %s', desc = "Trash selected files" },
  { on = "<F2>", run = "tasks:show", desc = "Show task manager" },
  { on = "o", run = "open --interactive", desc = "Open selected files interactively" },
  { on = "O", run = "open", desc = "Open selected files" },
  { on = "M", run = "plugin lsblk-mount", desc = "Open the drive mount manager" },
  { on = [ "c", "m" ], run = "plugin chmod", desc = "Chmod on selected files" },
]

[tasks]
prepend_keymap = [
  { on = "<C-[>", run = "noop" },
  { on = "<C-c>", run = "noop" },
  { on = "~", run = "noop" },
  { on = "w", run = "noop" },
  { on = "<F2>", run = "close", desc = "Close task manager" },
]
# append_keymap = []

[spot]
prepend_keymap = [
  { on = "<C-[>", run = "noop" },
  { on = "<C-c>", run = "noop" },
  { on = "~", run = "noop" },
]

[pick]
prepend_keymap = [
  { on = "<C-[>", run = "noop" },
  { on = "<C-c>", run = "noop" },
  { on = "~", run = "noop" },
]

[input]
prepend_keymap = [{ on = "<C-[>", run = "noop" }, { on = "~", run = "noop" }]

[confirm]
prepend_keymap = [
  { on = "<C-[>", run = "noop" },
  { on = "<C-c>", run = "noop" },
  { on = "~", run = "noop" },
]

[cmp]
prepend_keymap = [
  { on = "<C-[>", run = "noop" },
  { on = "<C-c>", run = "noop" },
  { on = "~", run = "noop" },
  { on = "<Esc>", run = "close", desc = "Cancel completion" },
]

[help]
prepend_keymap = [
  { on = "<C-[>", run = "noop" },
  { on = "<C-c>", run = "noop" },
]
