#    Path                  Mode UID  GID  Age Argument
w /proc/sys/vm/swappiness - - - - 180
w /proc/sys/vm/watermark_boost_factor - - - - 0
w /proc/sys/vm/watermark_scale_factor - - - - 125
w /proc/sys/vm/page-cluster - - - - 0
