[colors]
foreground = "#a9b1d6"
background = "#1a1b26"
cursor_bg = "#c0caf5"
cursor_border = "#1a1b26"
cursor_fg = "#515c7e"
selection_bg = "#515c7e"
selection_fg = "#c0caf5"
ansi = [
  "#414868",
  "#f7768e",
  "#73daca",
  "#e0af68",
  "#7aa2f7",
  "#bb9af7",
  "#7dcfff",
  "#c0caf5",
]
brights = [
  "#414868",
  "#f7768e",
  "#73daca",
  "#e0af68",
  "#7aa2f7",
  "#bb9af7",
  "#7dcfff",
  "#c0caf5",
]
[colors.tab_bar.active_tab]
bg_color = '#1a1b26'
fg_color = '#c0c0c0'