[colors]
foreground = "#a9b1d6"
background = "#1a1b26"
cursor_bg = "#9aa5ce"
cursor_border = "#1a1b26"
cursor_fg = "#565f89"
selection_bg = "#565f89"
selection_fg = "#9aa5ce"
ansi = [
  "#414868",
  "#f7768e",
  "#9ece6a",
  "#e0af68",
  "#7aa2f7",
  "#bb9af7",
  "#7dcfff",
  "#c0caf5",
]
brights = [
  "#414868",
  "#f7768e",
  "#73daca",
  "#e0af68",
  "#7aa2f7",
  "#bb9af7",
  "#7dcfff",
  "#c0caf5",
]
