user_settings = {
  "__GL_SYNC_TO_VBLANK": "1",

  "PROTON_USE_NTSYNC": "1",
  "PROTON_ENABLE_WAYLAND": "1",

  "PROTON_PREFER_SDL": "1",

  "PROTON_ENABLE_NVAPI": "1",

  "PROTON_DLSS_UPGRADE": "1",
  "DXVK_NVAPI_DRS_NGX_DLSS_SR_OVERRIDE": "on",
  "DXVK_NVAPI_DRS_NGX_DLSS_FG_OVERRIDE": "on",
  "DXVK_NVAPI_DRS_NGX_DLSS_RR_OVERRIDE": "on",
  "DXVK_NVAPI_DRS_NGX_DLSS_SR_OVERRIDE_RENDER_PRESET_SELECTION": "render_preset_k",
  "DXVK_NVAPI_DRS_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION": "render_preset_latest",
  "DXVK_NVAPI_DRS_NGX_DLSS_RR_OVERRIDE_RENDER_PRESET_SELECTION": "render_preset_latest",

  "VKD3D_SWAPCHAIN_PRESENT_MODE": "IMMEDIATE"
}
