transaction_log            /var/log/btrbk.log

backend_local_user         btrfs-progs-sudo

lockfile                   /var/lock/btrbk.lock

snapshot_preserve_min   2d
snapshot_preserve       14d

target_preserve_min     no
target_preserve         20d 10w *m

volume /mnt/btr-pool
  snapshot_dir @snapshots
  target /mnt/btr-pool/@backups
  subvolume @
  subvolume @home
